hello:
  hello world from git1
spring:
  rabbitmq:
    host: 61.130.9.251
    port: 5672
    username: admin
    password: admin123
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh